# Generated by Django 3.2.20 on 2023-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('your_age', models.IntegerField()),
                ('your_emile', models.CharField(max_length=256)),
                ('your_phone_number', models.CharField(max_length=11)),
                ('your_picture', models.ImageField(blank=True, null=True, upload_to='user/picture/')),
                ('biography', models.TextField()),
                ('your_home_address', models.TextField()),
                ('your_projects', models.ManyToManyField(related_name='aboutmy', to='resume_maker.Projects')),
            ],
        ),
    ]
