# Generated by Django 3.2.20 on 2023-10-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Soft_skills',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='about',
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.TextField(),
        ),
    ]
