# Generated by Django 3.2.20 on 2023-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0005_remove_about_me_your_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='your_home_address',
            field=models.CharField(max_length=50),
        ),
    ]
