# Generated by Django 3.2.20 on 2023-10-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0006_alter_about_me_your_home_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_me',
            old_name='your_age',
            new_name='year_of_Birth',
        ),
    ]
